spring.application.name=ecommerce
server.port=5454

spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce
spring.datasource.username=postgres
spring.datasource.password=password

#jpa configurations
spring.jpa.show-sql=true
#for creating schemas and tables
spring.jpa.hibernate.ddl-auto=update
